<?php
/**
 * xenFramework (http://xenframework.com/)
 *
 * This file is part of the xenframework package.
 *
 * (c) Ismael Trascastro <itrascastro@xenframework.com>
 *
 * @link        http://github.com/xenframework for the canonical source repository
 * @copyright   Copyright (c) xenFramework. (http://xenframework.com)
 * @license     MIT License - http://en.wikipedia.org/wiki/MIT_License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace com\xenframework\calculator\tests\models;


use com\xenframework\calculator\models\CalculatorModel;

class CalculatorModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CalculatorModel
     */
    private $_calculator;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->_calculator = new CalculatorModel();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->_calculator = null;
    }

    /**
     * @dataProvider additionProvider
     */
    public function testAdd($op1, $op2, $expected)
    {
        $this->_calculator->setOp1($op1);
        $this->_calculator->setOp2($op2);
        $this->_calculator->add();
        $this->assertEquals($expected, $this->_calculator->getResult());
    }

    public function additionProvider()
    {
        return array(
            array(0, 0, 0),
            array(0, 1, 1),
            array(1, 0, 3),
            array(1, 1, 2)
        );
    }
}
 