<h1>Add</h1>
<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => $this->_router->toUrl('calculator', 'addDo'),
              'id'          => 'fr1',
              'method'      => 'post',
              'buttonValue' => 'Add',
              'controls'    => array(
                  array(
                      'field'   => 'op1',
                      'type'    => 'number'
                  ),
                  array(
                      'field'   => 'op2',
                      'type'    => 'number'
                  )
              )
        ))->show(); ?>
</div>