<h1><?php echo $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper', array('router' => $this->_router))->show(); ?>
</div>

<div>
    <table class="table table-hover">
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Password</th>
            <th>Role</th>
            <th colspan="2"></th>
        </tr>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?php echo $this->out($user->getId()); ?></td>
            <td><?php echo $this->out($user->getEmail()); ?></td>
            <td><?php echo $this->out($user->getPassword()); ?></td>
            <td><?php echo $this->out($user->getRole()); ?></td>
            <td><a href="<?php echo $this->_router->toUrl('users', 'update',
                    array('id' => $this->out($user->getId()))); ?>">update</a></td>
            <td><a href="<?php echo $this->_router->toUrl('users', 'remove',
                    array('id' => $this->out($user->getId()))); ?>">remove</a></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>
